services:
  backend:
    build: .
    image: drf_starter:latest
    container_name: drf_starter_backend
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - env/.env

  db:
    image: postgres:alpine3.20
    container_name: drf_starter_postgres
    env_file:
      - env/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
  
  storage:
    platform: linux/amd64
    image: scireum/s3-ninja:latest
    container_name: "drf_starter_storage"
    ports:
      - 9444:9000
    volumes:
      - storage:/home/s3

volumes:
  postgres_data:
  storage:

